-- Seed countries from countryMeta.ts
INSERT INTO countries (code, region, is_active, language_key, currency, climate_key, cost_level, residency_months, tax_employee, tax_corporate)
VALUES
  ('AT', 'europe', true, 'german', 'EUR', 'temperate', 'very_high', '60', '0–55%', '23%'),
  ('BE', 'europe', true, 'dutch_french', 'EUR', 'temperate', 'high', '60', '25–50%', '25%'),
  ('BG', 'europe', true, 'bulgarian', 'EUR', 'temperate', 'low', '60', '10%', '10%'),
  ('HR', 'europe', true, 'croatian', 'EUR', 'mediterranean', 'medium', '60', '20–30%', '18%'),
  ('CY', 'europe', true, 'greek_english', 'EUR', 'mediterranean', 'medium', '60', '0–35%', '12.5%'),
  ('CZ', 'europe', true, 'czech', 'CZK', 'temperate', 'medium', '60', '15–23%', '21%'),
  ('DK', 'europe', true, 'danish', 'DKK', 'temperate', 'very_high', '60', '37–52%', '22%'),
  ('EE', 'europe', true, 'estonian', 'EUR', 'temperate', 'medium', '60', '20%', '0–20%'),
  ('FI', 'europe', true, 'finnish', 'EUR', 'northern', 'high', '60', '12–44%', '20%'),
  ('FR', 'europe', true, 'french', 'EUR', 'temperate', 'high', '60', '0–45%', '25%'),
  ('DE', 'europe', true, 'german', 'EUR', 'temperate', 'high', '60', '14–45%', '15%'),
  ('GR', 'europe', true, 'greek', 'EUR', 'mediterranean', 'medium', '60', '9–44%', '22%'),
  ('HU', 'europe', true, 'hungarian', 'HUF', 'temperate', 'low', '60', '15%', '9%'),
  ('IS', 'europe', true, 'icelandic', 'ISK', 'subarctic', 'very_high', '48', '31–46%', '20%'),
  ('IE', 'europe', true, 'english', 'EUR', 'temperate', 'very_high', '60', '20–40%', '12.5%'),
  ('IL', 'asia', true, 'hebrew_arabic', 'ILS', 'mediterranean', 'high', '84', '10–50%', '23%'),
  ('IT', 'europe', true, 'italian', 'EUR', 'mediterranean', 'medium', '60', '23–43%', '24%'),
  ('LV', 'europe', true, 'latvian', 'EUR', 'temperate', 'medium', '60', '20–31%', '20%'),
  ('LT', 'europe', true, 'lithuanian', 'EUR', 'temperate', 'medium', '60', '15–32%', '15%'),
  ('LU', 'europe', true, 'french_german', 'EUR', 'temperate', 'very_high', '60', '0–42%', '17%'),
  ('MD', 'europe', true, 'romanian', 'MDL', 'temperate', 'low', '36', '12%', '12%'),
  ('MT', 'europe', true, 'maltese_english', 'EUR', 'mediterranean', 'medium', '60', '0–35%', '35%'),
  ('NL', 'europe', true, 'dutch', 'EUR', 'temperate', 'very_high', '60', '9–49.5%', '19–25.8%'),
  ('NO', 'europe', true, 'norwegian', 'NOK', 'northern', 'very_high', '60', '22–47%', '22%'),
  ('PL', 'europe', true, 'polish', 'PLN', 'temperate', 'low', '60', '12–32%', '19%'),
  ('PT', 'europe', true, 'portuguese', 'EUR', 'mediterranean', 'medium', '24', '14–48%', '21%'),
  ('RO', 'europe', true, 'romanian', 'RON', 'temperate', 'low', '60', '10%', '16%'),
  ('SK', 'europe', true, 'slovak', 'EUR', 'temperate', 'medium', '60', '19–25%', '21%'),
  ('SI', 'europe', true, 'slovenian', 'EUR', 'temperate', 'medium', '60', '16–50%', '19%'),
  ('ES', 'europe', true, 'spanish', 'EUR', 'mediterranean', 'medium', '60', '19–47%', '25%'),
  ('SE', 'europe', true, 'swedish', 'SEK', 'northern', 'very_high', '60', '32–52%', '20.6%'),
  ('CH', 'europe', true, 'german_french', 'CHF', 'alpine', 'very_high', '120', '0–40%', '12–21%'),
  ('GB', 'europe', true, 'english', 'GBP', 'temperate', 'high', '60', '20–45%', '25%'),
  ('IM', 'europe', true, 'english', 'GBP', 'temperate', 'high', '60', '10–20%', '0%'),
  ('JE', 'europe', true, 'english', 'GBP', 'temperate', 'high', '60', '20%', '0%'),
  ('GG', 'europe', true, 'english', 'GBP', 'temperate', 'high', '60', '20%', '0%'),
  ('TH', 'asia', true, 'thai', 'THB', 'tropical', 'low', '12', '5–35%', '20%'),
  ('VN', 'asia', true, 'vietnamese', 'VND', 'tropical', 'low', '12', '5–35%', '20%'),
  ('ID', 'asia', true, 'indonesian', 'IDR', 'tropical', 'low', '12', '5–35%', '22%')
ON CONFLICT (code) DO UPDATE SET region = EXCLUDED.region, language_key = EXCLUDED.language_key, currency = EXCLUDED.currency, climate_key = EXCLUDED.climate_key, cost_level = EXCLUDED.cost_level, residency_months = EXCLUDED.residency_months, tax_employee = EXCLUDED.tax_employee, tax_corporate = EXCLUDED.tax_corporate, updated_at = now();